-- ========================================================
-- ブログ統合プロジェクト — Supabase Schema & Migration SQL
-- 対象プロジェクト: cyzfspgnybrdgvmokhth
-- ========================================================

-- 1. 新規テーブル: brazil_diary_posts (ブラジル日記 Blogger 1,007件)
create table if not exists public.brazil_diary_posts (
  id bigint generated by default as identity primary key,
  entry_id integer,
  title text,
  url text,
  posted_at date,
  category text,
  body_text text,
  body_clean text,
  importance_score text,
  duplicate_of integer,
  source text default 'brazil_diary_blogger',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.brazil_diary_posts enable row level security;

-- 2. 新規テーブル: ameblo_posts (Ameblo ヘブライ語学習アーカイブ)
create table if not exists public.ameblo_posts (
  id bigint generated by default as identity primary key,
  entry_id text,
  title text,
  url text,
  posted_at date,
  category text,
  body_text text,
  body_clean text,
  importance_score text,
  source text default 'ameblo_hebrew_study',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.ameblo_posts enable row level security;

-- 3. 統合ビュー: blog_unified_feed
-- 年表 (memory_timeline_events), FC2 (fc2_epata_blog_posts), ブラジル日記 (brazil_diary_posts), Ameblo (ameblo_posts) を時系列順に統合
create or replace view public.blog_unified_feed as
select
  id::text as item_id,
  'timeline' as source,
  event_date as posted_date,
  title,
  coalesce(summary, body) as body,
  null::text as url,
  categories as tags,
  primary_category as category
from public.memory_timeline_events

union all

select
  id::text,
  'fc2_epata',
  posted_at,
  title,
  coalesce(body_clean, body_text),
  url,
  array[category],
  category
from public.fc2_epata_blog_posts

union all

select
  id::text,
  'brazil_diary',
  posted_at,
  title,
  coalesce(body_clean, body_text),
  url,
  array[category],
  category
from public.brazil_diary_posts

union all

select
  id::text,
  'ameblo',
  posted_at,
  title,
  coalesce(body_clean, body_text),
  url,
  array[category],
  category
from public.ameblo_posts;
