import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Database, 
  X, 
  CheckCircle2, 
  AlertCircle, 
  Play, 
  Download, 
  Copy, 
  Key, 
  Server, 
  ShieldCheck, 
  ListChecks, 
  Table, 
  Eye, 
  Sparkles,
  RefreshCw,
  Info
} from "lucide-react";
import { getSupabaseClient, DEFAULT_SUPABASE_PROJECT, DEFAULT_SUPABASE_URL } from "../lib/supabase";
import { importedPosts } from "../data/imported_posts";

interface SupabaseModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SupabaseModal: React.FC<SupabaseModalProps> = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState<"spec" | "sync" | "sql">("spec");
  const [supabaseUrl, setSupabaseUrl] = useState<string>(DEFAULT_SUPABASE_URL);
  const [serviceKey, setServiceKey] = useState<string>("");
  const [isSyncing, setIsSyncing] = useState<boolean>(false);
  const [syncProgress, setSyncProgress] = useState<{ current: number; total: number }>({ current: 0, total: importedPosts.length });
  const [syncLogs, setSyncLogs] = useState<string[]>([]);
  const [verificationResult, setVerificationResult] = useState<{ source: string; count: number }[] | null>(null);
  const [copiedStatus, setCopiedStatus] = useState<string | null>(null);

  const schemaSql = `-- ========================================================
-- ブログ統合プロジェクト — Supabase Schema & Migration SQL
-- 対象プロジェクト: cyzfspgnybrdgvmokhth
-- ========================================================

-- 1. 新規テーブル: brazil_diary_posts
create table if not exists public.brazil_diary_posts (
  id bigint generated by default as identity primary key,
  entry_id integer,
  title text,
  url text,
  posted_at date,
  category text,
  body_text text,
  body_clean text,
  importance_score text,
  duplicate_of integer,
  source text default 'brazil_diary_blogger',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.brazil_diary_posts enable row level security;

-- 2. 新規テーブル: ameblo_posts
create table if not exists public.ameblo_posts (
  id bigint generated by default as identity primary key,
  entry_id text,
  title text,
  url text,
  posted_at date,
  category text,
  body_text text,
  body_clean text,
  importance_score text,
  source text default 'ameblo_hebrew_study',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.ameblo_posts enable row level security;

-- 3. 統合ビュー: blog_unified_feed
create or replace view public.blog_unified_feed as
select
  id::text as item_id,
  'timeline' as source,
  event_date as posted_date,
  title,
  coalesce(summary, body) as body,
  null::text as url,
  categories as tags,
  primary_category as category
from public.memory_timeline_events

union all

select
  id::text,
  'fc2_epata',
  posted_at,
  title,
  coalesce(body_clean, body_text),
  url,
  array[category],
  category
from public.fc2_epata_blog_posts

union all

select
  id::text,
  'brazil_diary',
  posted_at,
  title,
  coalesce(body_clean, body_text),
  url,
  array[category],
  category
from public.brazil_diary_posts

union all

select
  id::text,
  'ameblo',
  posted_at,
  title,
  coalesce(body_clean, body_text),
  url,
  array[category],
  category
from public.ameblo_posts;
`;

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStatus(label);
    setTimeout(() => setCopiedStatus(null), 2000);
  };

  const handleRunSupabaseSync = async () => {
    if (!serviceKey.trim()) {
      alert("Supabase API Key (service_role / anon key) を入力してください。");
      return;
    }

    setIsSyncing(true);
    setSyncLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] Supabase クライアント初期化中 (${DEFAULT_SUPABASE_PROJECT})...`]);

    try {
      const client = getSupabaseClient(supabaseUrl, serviceKey);
      if (!client) {
        throw new Error("Supabase クライアントの作成に失敗しました。");
      }

      setSyncLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] Brazil Diary Blogger データ (${importedPosts.length} 件) の成形中...`]);

      const formattedRecords = importedPosts.map((post, idx) => {
        const rawContent = post.content || "";
        const bodyClean = rawContent
          .replace(/<br\s*\/?>/gi, "\n")
          .replace(/<\/?[^>]+(>|$)/g, "")
          .trim();

        let postedAt = "2011-01-01";
        if (post.published) {
          postedAt = post.published.split("T")[0];
        }

        let entryId: number | null = null;
        if (post.id && !isNaN(Number(post.id))) {
          const num = parseInt(post.id, 10);
          if (num < 2147483647 && num > -2147483648) {
            entryId = num;
          } else {
            entryId = idx + 1;
          }
        } else {
          entryId = idx + 1;
        }

        return {
          entry_id: entryId,
          title: post.title || "無題",
          url: post.url || "",
          posted_at: postedAt,
          category: post.labels && post.labels.length > 0 ? post.labels[0] : "ブラジル日記",
          body_text: rawContent,
          body_clean: bodyClean,
          importance_score: post.importance_score || "C",
          source: "brazil_diary_blogger"
        };
      });

      setSyncLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] brazil_diary_posts テーブルへのバッチインサート開始...`]);

      const BATCH_SIZE = 50;
      let successCount = 0;

      for (let i = 0; i < formattedRecords.length; i += BATCH_SIZE) {
        const chunk = formattedRecords.slice(i, i + BATCH_SIZE);
        const { error } = await client.from("brazil_diary_posts").upsert(chunk);

        if (error) {
          console.error("Batch insert error:", error);
          setSyncLogs((prev) => [...prev, `[ERROR] バッチ ${i / BATCH_SIZE + 1} 失敗: ${error.message}`]);
        } else {
          successCount += chunk.length;
          setSyncProgress({ current: successCount, total: formattedRecords.length });
          setSyncLogs((prev) => [...prev, `[SUCCESS] ${successCount} / ${formattedRecords.length} 件インサート完了`]);
        }
      }

      setSyncLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] インポート完了！集計クエリを実行します...`]);

      // Run Verification Query
      const { data: unifiedData, error: viewError } = await client
        .from("blog_unified_feed")
        .select("source");

      if (viewError) {
        setSyncLogs((prev) => [...prev, `[WARN] 統合ビューのクエリに失敗しました: ${viewError.message}`]);
      } else if (unifiedData) {
        const counts: Record<string, number> = {};
        unifiedData.forEach((row: { source: string }) => {
          counts[row.source] = (counts[row.source] || 0) + 1;
        });
        const summaryArr = Object.entries(counts).map(([source, count]) => ({ source, count }));
        setVerificationResult(summaryArr);
        setSyncLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] 4ソース統合ビューのデータ確認成功！`]);
      }

    } catch (err: any) {
      console.error(err);
      setSyncLogs((prev) => [...prev, `[CRITICAL ERROR] ${err.message || err}`]);
    } finally {
      setIsSyncing(false);
    }
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-navy-950/70 backdrop-blur-sm"
        />

        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          className="relative w-full max-w-4xl bg-cream-50 rounded-xl border border-gold-500/30 shadow-2xl z-10 flex flex-col max-h-[90vh] overflow-hidden"
        >
          {/* Header */}
          <div className="bg-navy-900 text-cream-100 p-5 border-b border-gold-500/30 flex items-center justify-between shrink-0">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gold-500/10 rounded-lg border border-gold-500/30 text-gold-400">
                <Database className="w-6 h-6" />
              </div>
              <div>
                <h2 className="font-serif font-bold text-xl text-cream-50 flex items-center gap-2">
                  ブログ統合 Supabase 管理 & 仕様書
                </h2>
                <p className="text-xs text-cream-200/70 font-mono">
                  プロジェクトID: <span className="text-gold-400 font-bold">{DEFAULT_SUPABASE_PROJECT}</span>
                </p>
              </div>
            </div>

            <button
              onClick={onClose}
              className="text-cream-100/60 hover:text-cream-50 transition cursor-pointer p-1 rounded hover:bg-navy-800"
            >
              <X className="w-6 h-6" />
            </button>
          </div>

          {/* Navigation Tabs */}
          <div className="bg-navy-950 border-b border-gold-500/20 px-6 py-2 flex gap-2 shrink-0">
            <button
              onClick={() => setActiveTab("spec")}
              className={`px-4 py-2 rounded text-xs font-serif font-bold transition flex items-center gap-1.5 cursor-pointer ${
                activeTab === "spec"
                  ? "bg-gold-500 text-navy-950 shadow"
                  : "text-cream-100/70 hover:text-cream-50 hover:bg-navy-800"
              }`}
            >
              <ListChecks className="w-4 h-4" /> 設計仕様書 & 手順
            </button>
            <button
              onClick={() => setActiveTab("sync")}
              className={`px-4 py-2 rounded text-xs font-serif font-bold transition flex items-center gap-1.5 cursor-pointer ${
                activeTab === "sync"
                  ? "bg-gold-500 text-navy-950 shadow"
                  : "text-cream-100/70 hover:text-cream-50 hover:bg-navy-800"
              }`}
            >
              <RefreshCw className="w-4 h-4" /> Supabase 直接インポート
            </button>
            <button
              onClick={() => setActiveTab("sql")}
              className={`px-4 py-2 rounded text-xs font-serif font-bold transition flex items-center gap-1.5 cursor-pointer ${
                activeTab === "sql"
                  ? "bg-gold-500 text-navy-950 shadow"
                  : "text-cream-100/70 hover:text-cream-50 hover:bg-navy-800"
              }`}
            >
              <Table className="w-4 h-4" /> DDL & SQL スクリプト
            </button>
          </div>

          {/* Modal Body Content */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-cream-100/50">
            {activeTab === "spec" && (
              <div className="space-y-6">
                {/* Security Banner */}
                <div className="p-4 bg-emerald-50 border border-emerald-300 rounded-lg text-emerald-900 text-xs flex items-start gap-3">
                  <ShieldCheck className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <div className="space-y-1">
                    <span className="font-bold block text-sm">前提・セキュリティルール</span>
                    <p className="leading-relaxed">
                      RLSポリシーは <code className="bg-emerald-100 px-1 py-0.5 rounded font-mono">service-role-key</code> 前提とし、
                      publicロールへのSELECT許可（誰でも読めるポリシー）は追加しません。
                      アプリ側コードで <code className="bg-emerald-100 px-1 py-0.5 rounded font-mono">WHERE user_id = ...</code> を必ず付与します。
                    </p>
                  </div>
                </div>

                {/* Table Specifications */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Table 1: brazil_diary_posts */}
                  <div className="bg-cream-50 border border-gold-500/20 rounded-lg p-4 shadow-sm space-y-3">
                    <div className="flex items-center gap-2 text-navy-900 font-bold font-serif text-sm border-b border-cream-200 pb-2">
                      <Table className="w-4 h-4 text-gold-500" />
                      1. 新規テーブル: <code className="text-emerald-700 font-mono">brazil_diary_posts</code>
                    </div>
                    <p className="text-xs text-navy-700 leading-relaxed font-serif">
                      ブラジル日記（Blogger、2011〜2019、1,007件）の生本文アーカイブ。
                      <code className="bg-cream-200 px-1 rounded font-mono">fc2_epata_blog_posts</code> と同じ列構成。
                    </p>
                    <ul className="text-[11px] text-navy-600 space-y-1 font-mono bg-cream-100 p-2.5 rounded border border-cream-200">
                      <li>• entry_id (integer)</li>
                      <li>• title (text) / url (text)</li>
                      <li>• posted_at (date) / category (text)</li>
                      <li>• body_text (text) / body_clean (text)</li>
                      <li>• importance_score (text)</li>
                      <li>• source: 'brazil_diary_blogger'</li>
                    </ul>
                  </div>

                  {/* Table 2: ameblo_posts */}
                  <div className="bg-cream-50 border border-gold-500/20 rounded-lg p-4 shadow-sm space-y-3">
                    <div className="flex items-center gap-2 text-navy-900 font-bold font-serif text-sm border-b border-cream-200 pb-2">
                      <Table className="w-4 h-4 text-teal-500" />
                      2. 新規テーブル: <code className="text-teal-700 font-mono">ameblo_posts</code>
                    </div>
                    <p className="text-xs text-navy-700 leading-relaxed font-serif">
                      Ameblo「ヘブライ語学習」（ameblo.jp/shalom777）の投稿アーカイブ。
                    </p>
                    <ul className="text-[11px] text-navy-600 space-y-1 font-mono bg-cream-100 p-2.5 rounded border border-cream-200">
                      <li>• entry_id (text)</li>
                      <li>• title (text) / url (text)</li>
                      <li>• posted_at (date) / category (text)</li>
                      <li>• body_text (text) / body_clean (text)</li>
                      <li>• source: 'ameblo_hebrew_study'</li>
                    </ul>
                  </div>
                </div>

                {/* View 3: blog_unified_feed */}
                <div className="bg-cream-50 border border-gold-500/20 rounded-lg p-4 shadow-sm space-y-3">
                  <div className="flex items-center justify-between border-b border-cream-200 pb-2">
                    <div className="flex items-center gap-2 text-navy-900 font-bold font-serif text-sm">
                      <Eye className="w-4 h-4 text-amber-500" />
                      3. 統合ビュー: <code className="text-amber-700 font-mono">blog_unified_feed</code>
                    </div>
                    <span className="text-[10px] bg-amber-100 text-amber-800 px-2 py-0.5 rounded font-mono font-bold">
                      4ソース統合フィード
                    </span>
                  </div>
                  <p className="text-xs text-navy-700 leading-relaxed font-serif">
                    年表 (memory_timeline_events)、FC2 (fc2_epata_blog_posts)、ブラジル日記 (brazil_diary_posts)、Ameblo (ameblo_posts) を時系列順にまとめるビュー。
                  </p>
                  <div className="p-3 bg-navy-950 text-cream-100 rounded text-xs font-mono overflow-x-auto">
                    <code>select * from public.blog_unified_feed order by posted_date desc;</code>
                  </div>
                </div>

                {/* Execution Workflow */}
                <div className="bg-cream-50 border border-gold-500/20 rounded-lg p-4 shadow-sm space-y-3">
                  <h3 className="font-serif font-bold text-sm text-navy-900 flex items-center gap-2">
                    <ListChecks className="w-4 h-4 text-emerald-600" />
                    4. 実行順序フロー
                  </h3>
                  <ol className="text-xs text-navy-800 space-y-2 font-serif list-decimal list-inside pl-2">
                    <li><code className="font-mono text-emerald-700">brazil_diary_posts</code> テーブル作成 → Blogger アーカイブ投入</li>
                    <li><code className="font-mono text-teal-700">ameblo_posts</code> テーブル作成 → クロール投入</li>
                    <li>上記2テーブルの投入完了を確認後、<code className="font-mono text-amber-700">blog_unified_feed</code> ビューを作成</li>
                    <li>
                      <code className="font-mono text-navy-900 bg-cream-200 px-1">select count(*), source from blog_unified_feed group by source;</code> を実行し、全ソースの件数確認
                    </li>
                  </ol>
                </div>
              </div>
            )}

            {activeTab === "sync" && (
              <div className="space-y-6">
                <div className="p-4 bg-navy-900 text-cream-100 rounded-lg border border-gold-500/30 space-y-4">
                  <div className="flex items-center gap-2 text-gold-400 font-serif font-bold text-sm">
                    <Key className="w-4 h-4" />
                    Supabase 接続情報の設定
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
                    <div>
                      <label className="block text-cream-200/70 mb-1">Supabase URL</label>
                      <input
                        type="text"
                        value={supabaseUrl}
                        onChange={(e) => setSupabaseUrl(e.target.value)}
                        className="w-full bg-navy-950 border border-navy-700 rounded px-3 py-2 text-cream-50 focus:border-gold-500 outline-none"
                      />
                    </div>
                    <div>
                      <label className="block text-cream-200/70 mb-1">Service Role Key / Anon Key</label>
                      <input
                        type="password"
                        placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        value={serviceKey}
                        onChange={(e) => setServiceKey(e.target.value)}
                        className="w-full bg-navy-950 border border-navy-700 rounded px-3 py-2 text-cream-50 focus:border-gold-500 outline-none"
                      />
                    </div>
                  </div>

                  <div className="flex justify-end pt-2">
                    <button
                      onClick={handleRunSupabaseSync}
                      disabled={isSyncing}
                      className="bg-emerald-600 hover:bg-emerald-500 disabled:bg-emerald-800 text-cream-100 font-serif font-bold text-xs py-2.5 px-5 rounded shadow transition flex items-center gap-2 cursor-pointer"
                    >
                      {isSyncing ? (
                        <>
                          <RefreshCw className="w-4 h-4 animate-spin" />
                          インポート処理中 ({syncProgress.current} / {syncProgress.total})...
                        </>
                      ) : (
                        <>
                          <Play className="w-4 h-4 fill-current" />
                          Supabase に Brazil Diary ({importedPosts.length} 件) を直接インポート
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* Progress Bar */}
                {isSyncing && (
                  <div className="space-y-1">
                    <div className="flex justify-between text-xs font-mono text-navy-800">
                      <span>進捗率</span>
                      <span>{Math.round((syncProgress.current / syncProgress.total) * 100)}% ({syncProgress.current} / {syncProgress.total})</span>
                    </div>
                    <div className="w-full bg-cream-300 h-2.5 rounded-full overflow-hidden">
                      <div
                        className="bg-emerald-500 h-full transition-all duration-300"
                        style={{ width: `${(syncProgress.current / syncProgress.total) * 100}%` }}
                      />
                    </div>
                  </div>
                )}

                {/* Verification Result */}
                {verificationResult && (
                  <div className="p-4 bg-emerald-50 border border-emerald-300 rounded-lg space-y-3">
                    <h4 className="font-serif font-bold text-emerald-900 text-sm flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-emerald-600" />
                      統合ビュー (blog_unified_feed) ソース別件数確認
                    </h4>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                      {verificationResult.map((res) => (
                        <div key={res.source} className="bg-cream-50 p-2.5 rounded border border-emerald-200 text-center">
                          <span className="text-[10px] text-navy-600 font-mono block uppercase">{res.source}</span>
                          <span className="text-lg font-serif font-bold text-navy-950">{res.count} 件</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Logs Terminal */}
                <div className="bg-navy-950 text-cream-100 p-4 rounded-lg font-mono text-xs space-y-1 max-h-60 overflow-y-auto">
                  <div className="text-gold-400 font-bold border-b border-navy-800 pb-1 mb-2">
                    実行ログ
                  </div>
                  {syncLogs.length === 0 ? (
                    <span className="text-navy-500">待機中...「直接インポート」を押すとログが表示されます。</span>
                  ) : (
                    syncLogs.map((log, index) => (
                      <div key={index} className={log.includes("ERROR") ? "text-red-400" : log.includes("SUCCESS") ? "text-emerald-400" : "text-cream-200"}>
                        {log}
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

            {activeTab === "sql" && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="font-serif font-bold text-sm text-navy-900 flex items-center gap-2">
                    <Server className="w-4 h-4 text-gold-500" />
                    Supabase DDL & Migration SQL
                  </h3>

                  <div className="flex gap-2">
                    <button
                      onClick={() => copyToClipboard(schemaSql, "schema")}
                      className="bg-navy-800 hover:bg-navy-900 text-cream-100 text-xs px-3 py-1.5 rounded transition flex items-center gap-1 cursor-pointer font-serif"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      {copiedStatus === "schema" ? "コピーしました！" : "SQLをコピー"}
                    </button>
                  </div>
                </div>

                <pre className="bg-navy-950 text-gold-300/90 p-4 rounded-lg text-xs font-mono overflow-x-auto max-h-96 leading-relaxed border border-gold-500/20">
                  {schemaSql}
                </pre>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="bg-navy-900 text-cream-100/70 p-4 border-t border-gold-500/30 flex justify-between items-center text-xs font-serif shrink-0">
            <span className="flex items-center gap-1 text-gold-400">
              <Info className="w-3.5 h-3.5" />
              1,007 件の Blogger ブログデータ準備済み
            </span>

            <button
              onClick={onClose}
              className="bg-cream-100 hover:bg-gold-500 text-navy-950 px-4 py-1.5 rounded font-serif font-bold text-xs transition cursor-pointer"
            >
              閉じる
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
